### ISSUE TITLE
MVP LIST

### ISSUE THREAD

**Issue by TahjDev** [stellalc7/fullstack-proj#1]
- Inside of Board & Pins what do you mean by click a board => cllick a pin => pin details. That seems more like instructions. The MVP list just lets people what users can do and what is available to them.
- Discover feed on home page MVP should be before follows just because that is a lot more essential to pinterest.
- The bonus features MVP's should have the same format as the other MVP's

**Comment by stellalc7** [comment]
- Board & Pins rewritten to show what users can do and then what will be available to them
- Discover feed will be worked on before follows
- Bonus features rewritten to follow rest of MVP format

**Comment by TahjDev** [comment]
Ok looks good, only think is the bonus features should be in the same format ex: you have search bar it would have its own section
Search Bar
- then bullets about the functionality

**Comment by stellalc7** [comment]
Ah, understood - the search bonus has more details in it in the correct format I believe!
