### ISSUE TITLE
Backend Routes and Sample State and Frontend Routes

### ISSUE THREAD

**Issue by TahjDev** [stellalc7/fullstack-proj#3]
# Backend Routes
- Should there be a show route for a board to display all of its info?
- How would you get all the followers for a current user or what they follow?

# Sample State
- I dont see any information about following or being followed
- I dont see saves either

# FrontEnd Routes
- Would discover not have any sub components?

**Comment by stellalc7** [comment]
I saw my docs were approved, but I'll address / note your feedback. Thank you! Will focus on auth/splash right now.
